STITCH-981 - Check all builds for status for PR state

diff --git a/.evg.yml b/.evg.yml
--- a/.evg.yml
+++ b/.evg.yml
@@ -44,13 +44,17 @@ tasks:
             if ! [ "${is_patch}" = "true" ]; then
               exit 0
             fi
-            curl -H "Auth-Username: ${evg_rest_user}" -H "Api-Key: ${evg_rest_api_key}"  https://evergreen.mongodb.org/rest/v1/builds/${build_id} | python -c "import sys, json; tasks = json.load(sys.stdin)['tasks']; sys.exit(0) if all(tasks[task]['status'] == 'success' or task == 'github_pull_request_end'  for task in tasks) else sys.exit(1)"
-            if [ $? -eq 0 ]; then
-              state="success"
-            else
-              state="failure"
-            fi
-            echo $state > commit_state
+            BUILDS=( `curl -H "Auth-Username: ${evg_rest_user}" -H "Api-Key: ${evg_rest_api_key}"  https://evergreen.mongodb.org/rest/v1/versions/${version_id} | python -c "import sys, json; builds = json.load(sys.stdin)['builds']; print ' '.join(builds)"` )
+            for build in "${BUILDS[@]}"
+            do
+              curl -H "Auth-Username: ${evg_rest_user}" -H "Api-Key: ${evg_rest_api_key}"  https://evergreen.mongodb.org/rest/v1/builds/$build | python -c "import sys, json; tasks = json.load(sys.stdin)['tasks']; sys.exit(0) if all(tasks[task]['status'] == 'success' or task == 'github_pull_request_end'  for task in tasks) else sys.exit(1)"              
+              if [ $? -ne 0 ]; then
+                echo "failure" > commit_state
+                exit 0
+              fi
+            done
+
+            echo "success" > commit_state
       - func: "set_github_build_status"
 
   - name: run_tests
